// AUTO-GENERATED — do not edit manually.
// Source:      features/fixtures/fixtures.toml
// Regenerate:  pnpm exec nx run ux-uat:gen-fixtures
//
// To add or change fixture users, edit fixtures.toml, then re-run the
// gen-fixtures target.  Do NOT edit this file by hand.

import type { CurrentUserResponse, UserQueryModel } from '@/api/generated/model'
import { UserRole } from '@/api/generated/model'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FixtureUser {
  /** Friendly name used in BDD scenarios, e.g. 'Alice'. */
  name: string
  /** Plain-text password for login (test only). */
  password: string
  /** Shape returned by GET /api/v1/users/me. */
  profile: CurrentUserResponse
}

// ---------------------------------------------------------------------------
// Users — keyed by username
// ---------------------------------------------------------------------------

export const FIXTURE_USERS: Record<string, FixtureUser> = {
  alice01: {
    name: 'Alice',
    password: 'Alice Password 123!',
    profile: {
      id_: 'fixture-user-alice01',
      username: 'alice01',
      role: UserRole.super_admin,
      is_active: true,
    },
  },
  bobby01: {
    name: 'Bob',
    password: 'Bob Password 123!',
    profile: {
      id_: 'fixture-user-bobby01',
      username: 'bobby01',
      role: UserRole.user,
      is_active: true,
    },
  },
  charlie01: {
    name: 'Charlie',
    password: 'Charlie Password 123!',
    profile: {
      id_: 'fixture-user-charlie01',
      username: 'charlie01',
      role: UserRole.admin,
      is_active: true,
    },
  },
}

// ---------------------------------------------------------------------------
// Convenience: flat array for list endpoints
// ---------------------------------------------------------------------------

export const ALL_FIXTURE_USERS: UserQueryModel[] = Object.values(FIXTURE_USERS).map(
  (u) => ({
    id_: u.profile.id_,
    username: u.profile.username,
    role: u.profile.role,
    is_active: u.profile.is_active,
  })
)
