"""
Generates shadcn-admin/src/mocks/__fixtures__.generated.ts from
features/fixtures/fixtures.toml.

Run via:
    pnpm exec nx run ux-uat:gen-fixtures
  or directly:
    python scripts/uat/gen_mock_fixtures.py [--check]

flags:
  --check   Exit with code 1 if the generated file is out of date (CI use).
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from textwrap import dedent

# ── Paths ──────────────────────────────────────────────────────────────────────
_WORKSPACE = Path(__file__).resolve().parents[2]
_FIXTURES_TOML = _WORKSPACE / "features" / "fixtures" / "fixtures.toml"
_OUTPUT_TS = _WORKSPACE / "shadcn-admin" / "src" / "mocks" / "__fixtures__.generated.ts"


# ── Role mapping: TOML string → TypeScript UserRole member name ───────────────
# Must match app.domain.enums.user_role.UserRole values AND the TS UserRole enum.
_ROLE_TO_TS: dict[str, str] = {
    "super_admin": "UserRole.super_admin",
    "admin": "UserRole.admin",
    "user": "UserRole.user",
}


def _ts_bool(v: bool) -> str:
    return "true" if v else "false"


def _generate(raw: dict) -> str:
    users: dict[str, dict] = raw.get("users", {})

    lines: list[str] = [
        "// AUTO-GENERATED — do not edit manually.",
        "// Source:      features/fixtures/fixtures.toml",
        "// Regenerate:  pnpm exec nx run ux-uat:gen-fixtures",
        "//",
        "// To add or change fixture users, edit fixtures.toml, then re-run the",
        "// gen-fixtures target.  Do NOT edit this file by hand.",
        "",
        "import type { CurrentUserResponse, UserQueryModel } from '@/api/generated/model'",
        "import { UserRole } from '@/api/generated/model'",
        "",
        "// ---------------------------------------------------------------------------",
        "// Types",
        "// ---------------------------------------------------------------------------",
        "",
        "export interface FixtureUser {",
        "  /** Friendly name used in BDD scenarios, e.g. 'Alice'. */",
        "  name: string",
        "  /** Plain-text password for login (test only). */",
        "  password: string",
        "  /** Shape returned by GET /api/v1/users/me. */",
        "  profile: CurrentUserResponse",
        "}",
        "",
        "// ---------------------------------------------------------------------------",
        "// Users — keyed by username",
        "// ---------------------------------------------------------------------------",
        "",
        "export const FIXTURE_USERS: Record<string, FixtureUser> = {",
    ]

    for name, spec in users.items():
        username = spec["username"]
        password = spec["password"]
        role_ts = _ROLE_TO_TS[spec["role"]]
        is_active = _ts_bool(spec["is_active"])
        synthetic_id = f"fixture-user-{username}"

        lines += [
            f"  {username}: {{",
            f"    name: {name!r},",
            f"    password: {password!r},",
            "    profile: {",
            f"      id_: {synthetic_id!r},",
            f"      username: {username!r},",
            f"      role: {role_ts},",
            f"      is_active: {is_active},",
            "    },",
            "  },",
        ]

    lines += [
        "}",
        "",
        "// ---------------------------------------------------------------------------",
        "// Convenience: flat array for list endpoints",
        "// ---------------------------------------------------------------------------",
        "",
        "export const ALL_FIXTURE_USERS: UserQueryModel[] = Object.values(FIXTURE_USERS).map(",
        "  (u) => ({",
        "    id_: u.profile.id_,",
        "    username: u.profile.username,",
        "    role: u.profile.role,",
        "    is_active: u.profile.is_active,",
        "  })",
        ")",
        "",
    ]

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 if output is stale"
    )
    args = parser.parse_args()

    with _FIXTURES_TOML.open("rb") as fh:
        raw = tomllib.load(fh)

    generated = _generate(raw)

    if args.check:
        if not _OUTPUT_TS.exists():
            print(
                f"ERROR: {_OUTPUT_TS} does not exist — run gen-fixtures first.",
                file=sys.stderr,
            )
            return 1
        current = _OUTPUT_TS.read_text(encoding="utf-8")
        if current != generated:
            print(
                f"ERROR: {_OUTPUT_TS.relative_to(_WORKSPACE)} is out of date.\n"
                "       Run: pnpm exec nx run ux-uat:gen-fixtures",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {_OUTPUT_TS.relative_to(_WORKSPACE)} is up to date.")
        return 0

    _OUTPUT_TS.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_TS.write_text(generated, encoding="utf-8")
    user_count = len(raw.get("users", {}))
    print(f"Generated {_OUTPUT_TS.relative_to(_WORKSPACE)}  ({user_count} user(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
