"""add_email_phone_to_users

Revision ID: ef74f02cc8ff
Revises: e325187c1eeb
Create Date: 2026-03-11 17:00:14.222475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef74f02cc8ff"
down_revision: Union[str, None] = "e325187c1eeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=320), nullable=True))
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
