[Alice]
username = "alice01"
password = "Alice Password 123!"
role = "super_admin"
active = true

[Bob]
username = "bobby01"
password = "Bob Password 123!"
role = "user"
active = true

[Charlie]
username = "charlie01"
password = "Charlie Password 123!"
role = "admin"
active = true